### ISSUE TITLE
CLI: better `--help`

### ISSUE THREAD

**Issue by davidhund** [gajus/usus#16]
At the moment this is what I get:

![output of usus --help](https://www.dropbox.com/s/m8yfac95jo45k3y/Screenshot%202017-07-13%2012.56.35.png?dl=1)

… it would be really helpful to add all parameters and options. Preferably you would add a couple of usage examples [as you do in the readme](https://github.com/gajus/usus#using-via-the-command-line-interface-cli)

**Comment by gajus** [comment]
`usus render --help` :-)

However, it does not include usage examples. This is a simple addition.

**Comment by davidhund** [comment]
Oh wow, I completely missed that (`usus <command> --help`)!
It makes sense, obviously, but not from the README 😉

**Comment by gajus** [comment]
🎉
