### ISSUE TITLE
Skip `inlineStyles` when already inline?

### ISSUE THREAD

**Issue by davidhund** [gajus/usus#19]
This could be seen as a user error, but I noticed that `inlineStyles` basically duplicated my already-inline styles.

For my site I have all styles as an inline style block in the head. So no external `<link>`.

```
usus render --url https://valuedstandards.com/ --inlineStyles true > valuedstandards.html
```

.. will result in duplicate `<style>` blocks in the `<head>` :-)

Again: this might be to be expected since I should not have used `inlineStyles`, but it would be neat if this could be caught.

**Comment by gajus** [comment]
No, this sounds like a bug. Thank you for reporting.

**Comment by gajus** [comment]
🎉
