### ISSUE TITLE
Prevent inline styling

### ISSUE THREAD

**Issue by afontcu** [gajus/usus#30]
Hi!

when I run usus without any flag the output has all my styles inlined, which is undesirable as my html files grows up to 5000 LOC.

Shouldn't inline styling be disabled by default? Am I doing something wrong? I wrapped usus in a webpack plugin, but I'm just running it like this, nothing fancy

```js
const Usus = require('usus')
Usus.render('someUrl')
```

thanks for your time!

**Comment by gajus** [comment]
https://github.com/gajus/usus#configuration

**Comment by afontcu** [comment]
Hi, 

thanks, I read that `Using the --inlineStyles option returns HTML document with CSS inlined` but since I'm not providing that flag, shouldn't I expect the HTML document without the CSS inlined, but linked?

Thanks!

**Comment by gajus** [comment]
You need to provide `--inlineStyles false` as an option.
